/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningPathRouteImport } from './routes/learning-path'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCertificateCodeRouteImport } from './routes/verify-certificate.$code'
import { Route as TutorCoursesRouteImport } from './routes/tutor.courses'
import { Route as QuizCourseIdRouteImport } from './routes/quiz.$courseId'
import { Route as LearnSessionIdRouteImport } from './routes/learn.$sessionId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses_.$courseId'
import { Route as OrgOrgIdReportsRouteImport } from './routes/org.$orgId.reports'
import { Route as OrgOrgIdLearnersRouteImport } from './routes/org.$orgId.learners'
import { Route as OrgOrgIdDashboardRouteImport } from './routes/org.$orgId.dashboard'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathRoute = LearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateCodeRoute = VerifyCertificateCodeRouteImport.update({
  id: '/verify-certificate/$code',
  path: '/verify-certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorCoursesRoute = TutorCoursesRouteImport.update({
  id: '/tutor/courses',
  path: '/tutor/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCourseIdRoute = QuizCourseIdRouteImport.update({
  id: '/quiz/$courseId',
  path: '/quiz/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSessionIdRoute = LearnSessionIdRouteImport.update({
  id: '/learn/$sessionId',
  path: '/learn/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses_/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdReportsRoute = OrgOrgIdReportsRouteImport.update({
  id: '/org/$orgId/reports',
  path: '/org/$orgId/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdLearnersRoute = OrgOrgIdLearnersRouteImport.update({
  id: '/org/$orgId/learners',
  path: '/org/$orgId/learners',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdDashboardRoute = OrgOrgIdDashboardRouteImport.update({
  id: '/org/$orgId/dashboard',
  path: '/org/$orgId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$sessionId': typeof LearnSessionIdRoute
  '/quiz/$courseId': typeof QuizCourseIdRoute
  '/tutor/courses': typeof TutorCoursesRoute
  '/verify-certificate/$code': typeof VerifyCertificateCodeRoute
  '/org/$orgId/dashboard': typeof OrgOrgIdDashboardRoute
  '/org/$orgId/learners': typeof OrgOrgIdLearnersRoute
  '/org/$orgId/reports': typeof OrgOrgIdReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$sessionId': typeof LearnSessionIdRoute
  '/quiz/$courseId': typeof QuizCourseIdRoute
  '/tutor/courses': typeof TutorCoursesRoute
  '/verify-certificate/$code': typeof VerifyCertificateCodeRoute
  '/org/$orgId/dashboard': typeof OrgOrgIdDashboardRoute
  '/org/$orgId/learners': typeof OrgOrgIdLearnersRoute
  '/org/$orgId/reports': typeof OrgOrgIdReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/courses_/$courseId': typeof CoursesCourseIdRoute
  '/learn/$sessionId': typeof LearnSessionIdRoute
  '/quiz/$courseId': typeof QuizCourseIdRoute
  '/tutor/courses': typeof TutorCoursesRoute
  '/verify-certificate/$code': typeof VerifyCertificateCodeRoute
  '/org/$orgId/dashboard': typeof OrgOrgIdDashboardRoute
  '/org/$orgId/learners': typeof OrgOrgIdLearnersRoute
  '/org/$orgId/reports': typeof OrgOrgIdReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/learning-path'
    | '/login'
    | '/profile'
    | '/register'
    | '/verify-otp'
    | '/courses/$courseId'
    | '/learn/$sessionId'
    | '/quiz/$courseId'
    | '/tutor/courses'
    | '/verify-certificate/$code'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/learners'
    | '/org/$orgId/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/learning-path'
    | '/login'
    | '/profile'
    | '/register'
    | '/verify-otp'
    | '/courses/$courseId'
    | '/learn/$sessionId'
    | '/quiz/$courseId'
    | '/tutor/courses'
    | '/verify-certificate/$code'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/learners'
    | '/org/$orgId/reports'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/learning-path'
    | '/login'
    | '/profile'
    | '/register'
    | '/verify-otp'
    | '/courses_/$courseId'
    | '/learn/$sessionId'
    | '/quiz/$courseId'
    | '/tutor/courses'
    | '/verify-certificate/$code'
    | '/org/$orgId/dashboard'
    | '/org/$orgId/learners'
    | '/org/$orgId/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LearningPathRoute: typeof LearningPathRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LearnSessionIdRoute: typeof LearnSessionIdRoute
  QuizCourseIdRoute: typeof QuizCourseIdRoute
  TutorCoursesRoute: typeof TutorCoursesRoute
  VerifyCertificateCodeRoute: typeof VerifyCertificateCodeRoute
  OrgOrgIdDashboardRoute: typeof OrgOrgIdDashboardRoute
  OrgOrgIdLearnersRoute: typeof OrgOrgIdLearnersRoute
  OrgOrgIdReportsRoute: typeof OrgOrgIdReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-path': {
      id: '/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LearningPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate/$code': {
      id: '/verify-certificate/$code'
      path: '/verify-certificate/$code'
      fullPath: '/verify-certificate/$code'
      preLoaderRoute: typeof VerifyCertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/courses': {
      id: '/tutor/courses'
      path: '/tutor/courses'
      fullPath: '/tutor/courses'
      preLoaderRoute: typeof TutorCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$courseId': {
      id: '/quiz/$courseId'
      path: '/quiz/$courseId'
      fullPath: '/quiz/$courseId'
      preLoaderRoute: typeof QuizCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$sessionId': {
      id: '/learn/$sessionId'
      path: '/learn/$sessionId'
      fullPath: '/learn/$sessionId'
      preLoaderRoute: typeof LearnSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseId': {
      id: '/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/reports': {
      id: '/org/$orgId/reports'
      path: '/org/$orgId/reports'
      fullPath: '/org/$orgId/reports'
      preLoaderRoute: typeof OrgOrgIdReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/learners': {
      id: '/org/$orgId/learners'
      path: '/org/$orgId/learners'
      fullPath: '/org/$orgId/learners'
      preLoaderRoute: typeof OrgOrgIdLearnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/dashboard': {
      id: '/org/$orgId/dashboard'
      path: '/org/$orgId/dashboard'
      fullPath: '/org/$orgId/dashboard'
      preLoaderRoute: typeof OrgOrgIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LearningPathRoute: LearningPathRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LearnSessionIdRoute: LearnSessionIdRoute,
  QuizCourseIdRoute: QuizCourseIdRoute,
  TutorCoursesRoute: TutorCoursesRoute,
  VerifyCertificateCodeRoute: VerifyCertificateCodeRoute,
  OrgOrgIdDashboardRoute: OrgOrgIdDashboardRoute,
  OrgOrgIdLearnersRoute: OrgOrgIdLearnersRoute,
  OrgOrgIdReportsRoute: OrgOrgIdReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
