/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as SystemConfigRouteImport } from './routes/system-config'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as ContentModerationRouteImport } from './routes/content-moderation'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'

const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemConfigRoute = SystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentModerationRoute = ContentModerationRouteImport.update({
  id: '/content-moderation',
  path: '/content-moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/compliance': typeof ComplianceRoute
  '/content-moderation': typeof ContentModerationRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/system-config': typeof SystemConfigRoute
  '/tutors': typeof TutorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/compliance': typeof ComplianceRoute
  '/content-moderation': typeof ContentModerationRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/system-config': typeof SystemConfigRoute
  '/tutors': typeof TutorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/compliance': typeof ComplianceRoute
  '/content-moderation': typeof ContentModerationRoute
  '/escalations': typeof EscalationsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/system-config': typeof SystemConfigRoute
  '/tutors': typeof TutorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/compliance'
    | '/content-moderation'
    | '/escalations'
    | '/login'
    | '/payments'
    | '/system-config'
    | '/tutors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/compliance'
    | '/content-moderation'
    | '/escalations'
    | '/login'
    | '/payments'
    | '/system-config'
    | '/tutors'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/compliance'
    | '/content-moderation'
    | '/escalations'
    | '/login'
    | '/payments'
    | '/system-config'
    | '/tutors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  ComplianceRoute: typeof ComplianceRoute
  ContentModerationRoute: typeof ContentModerationRoute
  EscalationsRoute: typeof EscalationsRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  SystemConfigRoute: typeof SystemConfigRoute
  TutorsRoute: typeof TutorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-config': {
      id: '/system-config'
      path: '/system-config'
      fullPath: '/system-config'
      preLoaderRoute: typeof SystemConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-moderation': {
      id: '/content-moderation'
      path: '/content-moderation'
      fullPath: '/content-moderation'
      preLoaderRoute: typeof ContentModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  ComplianceRoute: ComplianceRoute,
  ContentModerationRoute: ContentModerationRoute,
  EscalationsRoute: EscalationsRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  SystemConfigRoute: SystemConfigRoute,
  TutorsRoute: TutorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
